//
//  MainInteractor.swift
//  AppCard
//
//  Created by N17430 on 2021/02/03.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic
{
//    func getList(curPage: Int, pageSize: Int)
    func getList()
    func _list() -> Main.List?
}

protocol MainDataStore
{
    //var name: String { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore
{
    var presenter: MainPresentationLogic?
    var worker = MainWorker()
    //var name: String = ""
    private(set) var list = Main.List(list: [])
    private(set) var lastKey: String = Main.GetList.FIRST_KEY
//    private(set) var curPage: Int = 0
    
    
    func getList()
    {
        worker.listPagination(startingAt: lastKey, size: Main.GetList.PAGE_SIZE) { (list) in
            if let list = list{
                self.list.append(contensOf: list)
                print(self.list.list.count)
                let response = Main.GetList.Response(list: self.list)
                self.presenter?.presentGetList(response: response)
                self.lastKey = self.list.object(indexOf: self.list.count-1)?.key ?? ""
            }
            else{ /* failure */ }            
        }
    }
    
//    func getList()
//    {
//        worker.listPagination(startingAt: updateDate, size: Main.GetList.PAGE_SIZE) { (list) in
//            if let list = list{
//                self.list.append(contensOf: list)
//                print(self.list.list.count)
//                self.updateDate = self.list.object(indexOf: self.list.count-1)?.updateDate ?? ""
//                let response = Main.GetList.Response(list: self.list)
//                self.presenter?.presentGetList(response: response)
//            }
//        }
//    }
    
    // MARK: Getter
    func _list() -> Main.List?
    {
        return self.list
    }
    
}
