//
//  MainInteractor.swift
//  AppCard
//
//  Created by N17430 on 2021/02/03.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic
{
    func getList()
    func _list() -> Main.List?
}

protocol MainDataStore
{
    //var name: String { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore
{
    var presenter: MainPresentationLogic?
    var worker = MainWorker()
    //var name: String = ""
    var list: Main.List?
    
    // MARK: Do something
    
//    func doSomething(request: Main.Something.Request)
//    {
//        worker = MainWorker()
//        worker?.doSomeWork()
//
//        let response = Main.Something.Response()
//        presenter?.presentSomething(response: response)
//    }
    
    func getList()
    {
        worker.list { (list) in
            if let list = list{
                self.list = list
            }
            else{ /* failure */ }
        }
    }
    
    // MARK: Getter
    func _list() -> Main.List?
    {
        return self.list
    }
    
}
