//
//  MainModels.swift
//  AppCard
//
//  Created by N17430 on 2021/02/03.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

enum Main
{
    // MARK: Use cases
    
    enum GetList
    {
        static let FIRST_KEY: String = "id_00000000000000"
        static let PAGE_SIZE: Int = 10
        struct Response
        {
            var list: List
        }
        struct ViewModel
        {
            var list: List
        }
    }
        
    // MARK: - ListElement Model
    struct ListElement: Codable {        
        var category : CategoryType?
        var displayType: DisplayType?
        var key, updateDate, openDate, closeDate, expireDate, dDayDate, corpName: String?
        var display: Display?
        
        // MARK: - Display
        struct Display: Codable {
            var headerTitle, mainTitle, subTitle, backImg: String?
            var labelImg, centerImg: String?
            var mainColor, fontColor: String?
            var labelText, iconImg, size, title: String?
            var rightImg: String?
            var backImgData, labelImgData, centerImgData, iconImgData, rightImgData: Data?
        }
        
        enum CategoryType: String, Codable {
            case coupon = "coupon"
            case feature = "feature"
            case news = "news"
            case noti = "noti"
            case shop = "shop"
        }
                
        enum DisplayType: String, Codable {
            case displayTypeDefault = "default"
            case noBack = "noBack"
            case none = "none"
        }
    }
    
}

extension Main{
    class List: NSObject{
        var list: [ListElement] = []
        var count: Int{
            return self.list.count
        }
        var imageDownloadCompletion: ((Main.List?) -> Void)?
         
        internal convenience init(list: [Main.ListElement] = [], imageDownloadCompletion: ((Main.List?) -> Void)? = nil, objs: [DataSnapshot] = []) {
            self.init()
            self.imageDownloadCompletion = imageDownloadCompletion
            self.list = list
            initWith(objs: objs)
//            initWithHigherOrdering(objs: objs)
        }
        
        /// 고차함수용: O(2n)
        /// - Parameter objs: <#objs description#>
        func initWithHigherOrdering(objs: [DataSnapshot] = []){
            guard objs.count > 0 else {return}
            var eleSet = Set<String>() // 중복제거용
            self.list = objs.map({ //(<#DataSnapshot#>) -> T in
                listElement(object: (key: $0.key as String, value: $0.value as AnyObject))
            })
            var index = 0
            self.list = self.list.filter({ //(<#Main.ListModel.ListElement#>) -> Bool in
                if $0.displayType == nil{return false}
                if let key = $0.key{
                    let oldCnt = eleSet.count
                    eleSet.insert(key)
                    if eleSet.count == oldCnt{return false}
                }
                else { return false }
                setImageData(ele: $0, idx: index)
                index += 1
                return true
            })
        }
        
        /// 인덱스로 접근: O(n)
        /// - Parameter objs: <#objs description#>
        func initWith(objs: [DataSnapshot] = []){
            guard objs.count > 0 else {return}
            var eles: [Main.ListElement] = []
            var eleSet = Set<String>() // 중복제거용
            for i in 0..<objs.count{
                let obj = objs[i]
                let ele = listElement(object: (key: obj.key as String, value: obj.value as AnyObject))
                if ele.displayType == nil{continue}
                let oldCnt = eleSet.count
                eleSet.insert(obj.key)
                if eleSet.count == oldCnt{continue}
                eles.append(ele)
                setImageData(ele: ele, idx: eles.count-1)
            }
            self.list = eles
        }
        
        
        /// ListElement set
        /// - Parameters:
        ///   - i: <#i description#>
        ///   - idx: self.listModel.list index
        /// - Returns: <#description#>
        private func listElement(object obj: (Dictionary<String, AnyObject>.Element)) -> Main.ListElement{
            var ele = Main.ListElement(key: obj.key)
            let i = obj.value
            if let val = i["category"] as? String{ ele.category = Main.ListElement.CategoryType(rawValue: val) }
            if let val = i["displayType"] as? String{ ele.displayType = Main.ListElement.DisplayType(rawValue: val) }
            if let val = i["updateDate"] as? String{ ele.updateDate = val }
            if let val = i["openDate"] as? String{ ele.openDate = val }
            if let val = i["closeDate"] as? String{ ele.closeDate = val }
            if let val = i["expireDate"] as? String{ ele.expireDate = val }
            if let val = i["dDayDate"] as? String{ ele.dDayDate = val }
            if let val = i["corpName"] as? String{ ele.corpName = val }
            if let d = i["display"] as? [String:AnyObject]{
                ele.display = Main.ListElement.Display()
                if let val = d["headerTitle"] as? String{ ele.display?.headerTitle = val }
                if let val = d["mainTitle"] as? String{ ele.display?.mainTitle = val }
                if let val = d["subTitle"] as? String{ ele.display?.subTitle = val }
                if let val = d["mainColor"] as? String{ ele.display?.mainColor = val }
                if let val = d["fontColor"] as? String{ ele.display?.fontColor = val }
                if let val = d["labelText"] as? String{ ele.display?.labelText = val }
                if let val = d["size"] as? String{ ele.display?.size = val }
                if let val = d["title"] as? String{ ele.display?.title = val }
                if let val = d["iconImg"] as? String{ele.display?.iconImg = val}
                if let val = d["backImg"] as? String{ele.display?.backImg = val}
                if let val = d["labelImg"] as? String{ele.display?.labelImg = val}
                if let val = d["centerImg"] as? String{ele.display?.centerImg = val}
                if let val = d["rightImg"] as? String{ele.display?.rightImg = val}
            }
            return ele
        }
        
        private func setImageData(ele: Main.ListElement, idx: Int){
            guard let d = ele.display else {return}
            if let val = d.iconImg, val.count > 0{
                FBStorage.imageData(fileName: val, getData: { data in
                    self.update(indexOf: idx) { (obj) in
                        obj.display?.iconImgData = data
                    }
                    //                            print("idx=\(idx) backImgData Set! fileName=\(val) getData=\(data) setData=\(ele.display?.rightImgData?.count)")
                    self.imageDownloadCompleteCancelingPrevious()
                })
            }
            if let val = d.backImg, val.count > 0{
                FBStorage.imageData(fileName: val, getData: { data in
                    self.update(indexOf: idx) { (obj) in
                        obj.display?.backImgData = data
                    }
                    //                            print("idx=\(idx) backImgData Set! fileName=\(val) getData=\(data) setData=\(ele.display?.rightImgData?.count)")
                    self.imageDownloadCompleteCancelingPrevious()
                })
            }
            if let val = d.labelImg, val.count > 0{
                FBStorage.imageData(fileName: val, getData: { data in
                    self.update(indexOf: idx) { (obj) in
                        obj.display?.labelImgData = data
                    }
                    //                            print("idx=\(idx) labelImgData Set! fileName=\(val) getData=\(data) setData=\(ele.display?.rightImgData?.count)")
                    self.imageDownloadCompleteCancelingPrevious()
                })
            }
            if let val = d.centerImg, val.count > 0{
                FBStorage.imageData(fileName: val, getData: { data in
                    self.update(indexOf: idx) { (obj) in
                        obj.display?.centerImgData = data
                    }
                    //                            print("idx=\(idx) centerImgData Set! fileName=\(val) getData=\(data) setData=\(ele.display?.rightImgData?.count)")
                    self.imageDownloadCompleteCancelingPrevious()
                })
            }
            if let val = d.rightImg, val.count > 0{
                FBStorage.imageData(fileName: val, getData: { data in
                    self.update(indexOf: idx) { (obj) in
                        obj.display?.rightImgData = data
                    }
                    //                            print("idx=\(idx) rightImgData Set! fileName=\(val) getData=\(data) setData=\(ele.display?.rightImgData?.count)")
                    self.imageDownloadCompleteCancelingPrevious()
                })
            }
        }
        
        private func imageDownloadCompleteCancelingPrevious(){
            NSObject.cancelPreviousPerformRequests(withTarget: self, selector: #selector(imageDownloadComplete), object: nil)
            self.perform(#selector(imageDownloadComplete), with: nil, afterDelay: 0.5)
        }
        
        @objc private func imageDownloadComplete(){
            self.imageDownloadCompletion?(self)
        }
        
        func append(contensOf list: Main.List){
            self.list.append(contentsOf: list.list)
        }
                
        func insertOnce(element: Main.ListElement, at: Int){
            guard let first = self.list.first, first.category! != .noti else {return}
            self.list.insert(element, at: at)
        }
        
        func object(indexOf idx: Int) -> Main.ListElement?{
            guard idx < list.count else { print("index에 해당하는 element가 없습니다 index=\(idx)"); return nil }
            return self.list[idx]
        }
        
        func update(indexOf idx: Int, block:((inout Main.ListElement)->Void)){
            guard idx < count else {return}
            block(&self.list[idx])
        }
        
    }
}
