//
//  MainWorker.swift
//  AppCard
//
//  Created by N17430 on 2021/02/03.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainWorker
{
    
//    func list(completion: ((Main.List?) -> Void)?){
//        FBDatabase.list { (objs) in
//            if let objs = objs, case let list = Main.List(objs: objs), list.list.count > 0{
//                completion?(list)
//            }
//            else{ print("아이템 갯수=0"); completion?(nil) }
//        }
//    }
    
    func listPagination(startingAt key: String, size: Int, completion: ((Main.List?) -> Void)?){
        FBDatabase.listPagination(startingAt: key, size: UInt(size)) { (objs) in
            if let objs = objs{ // list.list.count > 0
                Main.List(imageDownloadCompletion: { list in
                    print("imageDownloadCompletion!")
                    completion?(list)
                }, objs: objs)
            }
            else{ print("아이템 갯수=0"); completion?(nil) }
        }
    }
}
